load_paths:
  - test/src
  - test/vendor
  - assets
  - polyfills
  - src

logical_paths:
  - trix.js
  - test.js

build:
  logical_paths:
    - trix.js
    - trix-core.js
  path: dist
  js_compressor: uglifier
