Trix.config.lang =
  bold: "Bold"
  bullets: "Bullets"
  code: "Code"
  heading1: "Heading"
  heading2: "Subheading"
  indent: "Increase Level"
  italic: "Italic"
  link: "Link"
  numbers: "Numbers"
  outdent: "Decrease Level"
  quote: "Quote"
  redo: "Redo"
  remove: "Remove"
  small: "Small"
  strike: "Strikethrough"
  undo: "Undo"
  unlink: "Unlink"
  url: "URL"
  urlPlaceholder: "Enter a URL…"
